const diningArea = [
    'general floor area broom-swept and clean',
    'floors along walls and baseboards clean',
    'floor mat clean (not soiled) and broom swept',
    'baseboards clean and well-maintained',
    'table bases wiped down and clean',
    'booths and banquetes wiped down and clean',
    'booths and banquetes well-maintained',
    'booth platorms clean and well-maintained',
    'dining chair seats wiped down and clean',
    'dining chair cracks free of crumbs and debris',
    'dining chair legs clean',
    'tabletops wiped down and clean',
    'condiments fully stocked, organized and clean at each table',
    'condiment caddies clean, well-maintained, and chalkboards legible and not smeared',
    'Finney tablets clean and fully operational',
    'window ledges clean and free of debris',
    'windows clean',
    'TV’s clean and in good repair',
    'perimeter walls clean and well-maintained',
    'service stations well-organized and clean',
    'service stations well-maintained',
    'POS systems clean and in good repair',
    'waste bins (interior and exterior ) clean',
    'highchairs and booster seats clean and properly stored',
    'restroom corridor floor broom swept and clean along walls',
    'restroom corridor walls clean and well-maintained',
    'restroom corridor mat clean (not soiled) and broom swept',
    'high ceiling area clean and well-maintained (lighting fixtures, ductwork, etc.)',
    'air-conditioning vents clean and dust free',
    'lighting fixtures (including exit signs) fully operational - no burnt-out light bulbs',
    'no evidence of pest activity (10 points)'
];

export default diningArea;